# CI / quality gates.

.PHONY: check test lint format format-check doc doc-open doc-clean clean ci audit deny coverage

check:
	cd $(ROOT) && $(CARGO) check --workspace

test:
	cd $(ROOT) && $(CARGO) test --workspace

## Requires `cargo install cargo-llvm-cov`. Writes `coverage/lcov.info`.
## Uses the stable toolchain so llvm-cov finds instrumented objects.
coverage:
	cd $(ROOT) && mkdir -p coverage && RUSTUP_TOOLCHAIN=stable $(CARGO) llvm-cov --workspace --lcov \
		--ignore-filename-regex 'examples/|crates/serenade-cli/|serenade-console/src/(interactive\.rs|commands/)|/serenade-contracts/src/tests\.rs' \
		--output-path coverage/lcov.info

format:
	cd $(ROOT) && $(CARGO) fmt

format-check:
	cd $(ROOT) && $(CARGO) fmt --check

lint: format-check
	cd $(ROOT) && $(CARGO) clippy --workspace --all-targets -- $(CLIPPY_FLAGS)

## rustdoc → `docs/api-rust/` (GitHub Pages publish folder).
DOC_OUT ?= $(ROOT)/target/doc
DOC_CRATE ?= serenade_kernel

doc:
	cd $(ROOT) && RUSTDOCFLAGS="$(RUSTDOCFLAGS)" $(CARGO) doc --workspace --no-deps --features serenade-cache/redis
	@test -d "$(DOC_OUT)" || (echo "missing $(DOC_OUT)"; exit 1)
	@rm -rf $(ROOT)/docs/api-rust
	@mkdir -p $(ROOT)/docs/api-rust
	@cp -a "$(DOC_OUT)/." $(ROOT)/docs/api-rust/
	@printf '%s\n' \
		'<!DOCTYPE html>' \
		'<html lang="en">' \
		'<head>' \
		'<meta charset="utf-8">' \
		'<meta http-equiv="refresh" content="0; url=$(DOC_CRATE)/index.html">' \
		'<title>Serenade - Rust API docs</title>' \
		'<link rel="canonical" href="$(DOC_CRATE)/index.html">' \
		'<script>location.replace("$(DOC_CRATE)/index.html");</script>' \
		'</head>' \
		'<body><p><a href="$(DOC_CRATE)/index.html">Serenade API documentation</a></p></body>' \
		'</html>' \
		> $(ROOT)/docs/api-rust/index.html
	@touch $(ROOT)/docs/api-rust/.nojekyll
	@printf '%s\n' \
		'# Rust API documentation (rustdoc)' \
		'' \
		'Open [`$(DOC_CRATE)/index.html`]($(DOC_CRATE)/index.html) (root [`index.html`](index.html) redirects there).' \
		> $(ROOT)/docs/api-rust/README.md
	@echo "docs/api-rust/ updated - open docs/api-rust/index.html"

doc-open: doc
	@xdg-open $(ROOT)/docs/api-rust/index.html 2>/dev/null \
		|| open $(ROOT)/docs/api-rust/index.html 2>/dev/null \
		|| echo "Open docs/api-rust/index.html in a browser"

doc-clean:
	rm -rf $(ROOT)/docs/api-rust
	mkdir -p $(ROOT)/docs/api-rust
	@printf '%s\n' \
		'# Rust API documentation (rustdoc)' \
		'' \
		'Generated by `make doc`. Open [`index.html`](index.html) after building.' \
		> $(ROOT)/docs/api-rust/README.md

## Requires `cargo install cargo-audit`.
## RUSTSEC-2026-0258: actix-http 3.x pins h2 0.3; fix is only on h2 >= 0.4.16.
## Wasmer stack advisories: same ignores as deny.toml for serenade-sandbox.
audit:
	cd $(ROOT) && $(CARGO) audit \
		--ignore RUSTSEC-2026-0258 \
		--ignore RUSTSEC-2024-0436 \
		--ignore RUSTSEC-2026-0173 \
		--ignore RUSTSEC-2025-0141

## Requires `cargo install cargo-deny`.
deny:
	cd $(ROOT) && $(CARGO) deny check

ci: lint test doc audit deny

clean:
	cd $(ROOT) && $(CARGO) clean
